version: 2.1

orbs:
  win: circleci/windows@2.2.0

workflows:
  version: 2
  build-win:
    jobs:
      - build-win

jobs:
  build-win:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'
